version: '3'

services:
    train:
        container_name: gsg-train
        image: gsg-train-image
        command: dvc repro experiments/eurlex57k/dvc.yaml
        build:
            context: ../
            dockerfile: docker/Dockerfile
        volumes:
            - ../datasets:/app/datasets
            - ./model:/app/experiments/eurlex57k/model
        environment:
            - NUM_DATALOADER_WORKERS=1
